# Generated by Django 3.0.5 on 2020-06-01 01:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('precounitario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.MateriaPrima')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.MateriaPrima')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perda',
            },
        ),
        migrations.CreateModel(
            name='EstoqueHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeantes', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valorantes', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('valorunitarioantes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantidadedepois', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valordepois', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('valorunitariodepois', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.Compra')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.MateriaPrima')),
                ('perda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.Perda')),
            ],
            options={
                'db_table': 'estoque_historico',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('valorunitario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.MateriaPrima')),
            ],
            options={
                'db_table': 'estoque',
            },
        ),
    ]
