# Generated by Django 3.0.5 on 2020-08-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20200809_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
