# Generated by Django 3.0.5 on 2020-06-01 01:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Canal de Venda',
                'db_table': 'canalvenda',
                'unique_together': {('estabelecimento', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Categoria',
                'db_table': 'categoria',
                'ordering': ['nome', '-ativo'],
                'permissions': (('categorias', 'Categorias'),),
                'unique_together': {('estabelecimento', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('porcentagem', 'Porcentagem'), ('real', 'Real')], default='porcentagem', max_length=11)),
                ('valor', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Custo',
                'db_table': 'custo',
                'unique_together': {('estabelecimento', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_medida', models.CharField(choices=[('un', 'Unidade'), ('gr', 'Grama'), ('cm', 'Centímetros'), ('ql', 'Quilo'), ('ml', 'Mililitro (ml)'), ('lt', 'Litro'), ('cm2', 'Centímetro quadrado'), ('mt2', 'Metro quadrado')], default='un', max_length=3)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Categoria')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
            ],
            options={
                'db_table': 'materiaprima',
                'unique_together': {('nome', 'categoria', 'tipo_medida')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('materiacompleto', models.BooleanField(default=False)),
                ('canalcompleto', models.BooleanField(default=False)),
                ('custocompleto', models.BooleanField(default=False)),
                ('precocompleto', models.BooleanField(default=False)),
                ('preco', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('lucro', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('canais', models.ManyToManyField(to='produtos.CanalVenda')),
                ('custos', models.ManyToManyField(to='produtos.Custo')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Produto',
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='ProdutoMateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=16)),
                ('materiaprima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.MateriaPrima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto')),
            ],
            options={
                'db_table': 'produtomateriaprima',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='materias',
            field=models.ManyToManyField(through='produtos.ProdutoMateriaPrima', to='produtos.MateriaPrima'),
        ),
    ]
