# Generated by Django 3.0.5 on 2020-06-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='precobase',
        ),
    ]
