# Generated by Django 3.0.5 on 2020-06-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
