# Generated by Django 3.0.5 on 2020-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='updatepreco',
            field=models.BooleanField(default=False),
        ),
    ]
